buildscript {
    repositories {
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        mavenCentral()
    }
}

plugins {
    id 'eclipse'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.88'
    id 'io.freefair.lombok' version '8.13.1'
    id 'dev.vfyjxf.modaccessor' version '1.2.1'
}

modAccessor {
    createTransformConfiguration(configurations.compileOnly)
    accessTransformerFiles = project.files('src/main/resources/META-INF/accesstransformer.cfg')
}

group = mod_group_id
version = mod_version

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    // Specify the version of NeoForge to use.
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        guide {
            client()
            systemProperty 'guideme.ae2.guide.sources', file('run/resourcepacks/temp/assets/expandedae/ae2guide').absolutePath
            // This is only needed if you are developing an addon and it should be your mod id
            systemProperty "guideme.ae2.guide.sourcesNamespace", "expandedae"
            systemProperty('guideme.showOnStartup', 'ae2:index.md') // Start at index.md
        }

        client {
            client()
            //jvmArgument("-XX:+AllowEnhancedClassRedefinition")
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }


        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        data {
            data()

            // example of overriding the workingDirectory set in configureEach above, uncomment if you want to use it
            // gameDirectory = project.file('run-data')

            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }
    mods {
        // define mod <-> source bindings
        // these are used to tell the game which sources are for which mod
        // mostly optional in a single mod project
        // but multi mod projects should define one per mod
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    mavenLocal()
    maven {
        url = "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/"
    }
    maven {
        url = uri("https://modmaven.dev/")
        content {
            includeGroup "appeng"
            includeGroup "de.mari_023"
        }
    }
    maven { // Registrate
        url = "https://maven.tterrag.com/"
    }
    maven {
        name = "Illusive Soulworks maven"
        url = "https://maven.theillusivec4.top/"
    }
    maven {
        name = "firstdarkdev"
        url = "https://maven.firstdarkdev.xyz/snapshots"
    }
    maven {
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
}

dependencies {
    //implementation "curse.maven:applied-energistics-2-223794:6488853"
    accessCompileOnly("org.appliedenergistics:appliedenergistics2:19.2.10")
    implementation "org.appliedenergistics:appliedenergistics2:19.2.10"
    implementation "curse.maven:ex-pattern-provider-892005:6505209"
    implementation "curse.maven:glodium-957920:5821676"
    implementation "curse.maven:guideme-1173950:6488254"
    implementation "curse.maven:advancedae-1084104:6225993"

    jarJar(implementation "de.mari_023:ae2wtlib_api:$ae2wtlib_version")
    runtimeOnly "de.mari_023:ae2wtlib:$ae2wtlib_version"
    compileOnly "de.mari_023:ae2wtlib:$ae2wtlib_version"
    runtimeOnly "curse.maven:appliede-1009940:6500056"
    runtimeOnly "curse.maven:projecte-226410:6611984"

    //implementation "curse.maven:applied-energistics-2-wireless-terminals-459929:6437277"
    implementation "curse.maven:architectury-api-419699:5786327"
    implementation "curse.maven:curios-309927:6401872"

    implementation "curse.maven:applied-flux-965012:6649565"
    runtimeOnly "curse.maven:geckolib-388172:6304958"
    implementation "curse.maven:mega-cells-622112:6517566"
    runtimeOnly "curse.maven:cloth-config-348521:5729127"
    //Cell implementations
    //compileOnly "curse.maven:ars-energistique-905641:6203425"
    //implementation "curse.maven:applied-experienced-1157608:6616730"
    //implementation "curse.maven:applied-mekanistics-574300:5978711"

    //play testing
    runtimeOnly "curse.maven:soulplied-energistics-1143614:6083831"
    runtimeOnly "curse.maven:industrial-foregoing-souls-904394:6235883"
    runtimeOnly "curse.maven:titanium-287342:6443608"
    runtimeOnly "curse.maven:industrial-foregoing-266515:6502376"
    runtimeOnly "curse.maven:mekanism-268560:6486993"

    runtimeOnly "curse.maven:enderdrives-1226739:6482292"
    implementation "curse.maven:bigger-ae2-1013772:6587078"

    compileOnly "dev.emi:emi-neoforge:${emi_version}:api"
    //runtimeOnly "dev.emi:emi-neoforge:${emi_version}"
    runtimeOnly "curse.maven:jade-324717:6667790"

    compileOnly("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")
    compileOnly("mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}")
    runtimeOnly("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")
    implementation "curse.maven:ae2-jei-integration-1074338:5748513"
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [minecraft_version      : minecraft_version,
                             minecraft_version_range: minecraft_version_range,
                             neo_version            : neo_version,
                             neo_version_range      : neo_version_range,
                             loader_version_range   : loader_version_range,
                             mod_id                 : mod_id,
                             mod_name               : mod_name,
                             mod_license            : mod_license,
                             mod_version            : mod_version,
                             mod_authors            : mod_authors,
                             mod_description        : mod_description]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version   : minecraft_version, minecraft_version_range: minecraft_version_range,
            neoforge_version         : neo_version, neoforge_version_range: neo_version_range,
            loader_version_range: loader_version_range,
            mod_id              : mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
            mod_authors         : mod_authors, mod_description: mod_description,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

tasks.withType(Jar).configureEach {
    destinationDirectory.set(file("$rootDir/jar"))
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

tasks.withType(Copy).configureEach {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

//tasks.runClient.dependsOn(tasks.runData)